version: 1
disable_existing_loggers: False
formatters:
  default:
    format: "[%(asctime)s] [%(levelname)s] %(name)s: %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  console:
    class: logging.StreamHandler
    formatter: default
    level: INFO
    stream: ext://sys.stdout
loggers:
  console-api:
    handlers: [console]
    level: INFO
    propagate: no
root:
  level: INFO
  handlers: [console]
